-- Buat tabel log_level_air
CREATE TABLE IF NOT EXISTS log_level_air (
    id bigint generated by default as identity primary key,
    waktu text not null,
    status text not null,
    persen integer not null,
    jarak_cm real not null
);

-- Buat index untuk mempercepat query berdasarkan waktu
CREATE INDEX IF NOT EXISTS idx_waktu ON log_level_air (waktu);

-- Buat tabel log_alarm
CREATE TABLE IF NOT EXISTS log_alarm (
    id bigint generated by default as identity primary key,
    waktu_mulai text not null,
    waktu_selesai text,
    cara_selesai text
);

-- Matikan sistem keamanan RLS (Row-Level Security) agar laptop & Vercel bebas mengirim data
ALTER TABLE log_level_air DISABLE ROW LEVEL SECURITY;
ALTER TABLE log_alarm DISABLE ROW LEVEL SECURITY;
